refactor: RFC 334 Add NIST P keys concrete examples
hyperledger/aries-rfcs pull request #575
Opened 2020-12-14 18:22 UTC by Baha-sk

Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

2020-12-15 14:36 UTC, llorllale approved these changes

2020-12-15 22:00 UTC, kdenhartog requested changes
Looking through this I'm left a bit confused about the forms being described. For much of the DIDCommV1 stuff I didn't think we had moved to a standards compliant JWE for this work, but I haven't been tracking it for quite some time.

For the DIDCommV2 work most of these key types are supported, but many of the examples are presenting a set of use cases (compact for single recipient, using ECDH-ES to name two particular cases) that aren't defined in the didcomm-messaging spec. 

What's the intent of description for this topic? Is it focused on DIDCommV1 pack/unpack style or DIDCommV2 stuff?

2020-12-15 23:05 UTC, llorllale commented
@kdenhartog 

> What's the intent of description for this topic? Is it focused on DIDCommV1 pack/unpack style or DIDCommV2 stuff?

The intent is to advance RFC 0334 for use in DIDComm V1 with an eye on AIP 2.0.

This has nothing to do with DIDComm V2.

2020-12-15 23:19 UTC, kdenhartog commented
> @kdenhartog
> 
> > What's the intent of description for this topic? Is it focused on DIDCommV1 pack/unpack style or DIDCommV2 stuff?
> 
> The intent is to advance RFC 0334 for use in DIDComm V1 with an eye on AIP 2.0.
> 
> This has nothing to do with DIDComm V2.

Ahh interesting that may leave us with 3 potential formats that have to be considered at a DIDComm endpoint then while looking to migrate DIDCommV1 to DIDCommV2? E.g. RFC 0019 (old JWE derived pack/unpack), RFC 0334 (Includes Anoncrypt/Authcrypt with similar key types), and the DIDCommV2 version (albeit DIDCommV2 is just a subset of RFC 0334 from the looks of it)

I think this is going to make AIP 2.0 effectively compliant at the envelope layer at least, but probably still going to need mime type adjustments and such to indicate the change in version.

2020-12-15 23:20 UTC, kdenhartog reviewed
Changing review to comment now that I understand purpose better. I think I need to do some more reading on AIP 2.0 to consider the transition path to DIDCommV2 (e.g. probably transition to AIP 2.0 to AIP 2.1/AIP 3.0)

2021-01-11 15:56 UTC, Baha-sk commented on features/0334-jwe-envelope/anoncrypt-examples.md
> +  }],
currently our Ares-Framework-Go JWE packers don't expose aad directly, but I can probably add aad in these examples (in a future PR though)

2021-03-25 01:38 UTC, Baha-sk commented on features/0334-jwe-envelope/anoncrypt-examples.md
> +  }],
I ended up adding aad in this pr @kdenhartog

2021-03-25 01:41 UTC, Baha-sk commented
@kdenhartog @andrewwhitehead, I've updated this PR to include integrity checks as recommended by @kdenhartog's [comment](https://github.com/hyperledger/aries-rfcs/pull/575#discussion_r542930798) above.

The examples now include both X25519 and NIST P curved keys.
I've also used DIDComm V2's media types in the examples to be compatible.

This pr is ready for review/merge

2021-03-25 16:16 UTC, merged

2021-03-25 16:16 UTC, swcurran commented
Merged per discussion on Aries Working Group call.