Cleanup RFCs for mkdocs website generation
hyperledger/aries-rfcs pull request #826
Opened 2024-03-30 19:47 UTC by swcurran

The vast majority of the changes are just to add "mailto:" to the front of the email addresses in the RFCs -- that was missed in the templates, and it carried into the RFCs themselves.

A few other cleanups of paths, and tweaks to the generator.  In the process, a couple of clarifications were made -- minor, to do with things that have changed over time.

2024-05-02 21:44 UTC, swcurran commented
Lots of files changed, but only a few things to look at:

* Index and mkdocs have the same set of changes as the last change.  Not entirely sure why they are being redone.
  * If the index/mkdocs are right, the statuses are right as the those files are generated.
* Proper "mailto:" added to all the Authors lines. Trust me 🙂
* Clean ups of naked URLs and other things that generated mkdocs warnings/errors.

So really -- just make sure that the index is right and all good.

And one more note -- RFC 0685 used to have as it's title line "RFC 0212", so that is fixed (someone forgot to change the RFC number in the title), and PR 0799 has moved from top to bottom of proposed - back in alpha order.

2024-05-03 16:42 UTC, JamesKEbert requested changes
Looks good. Just some minor catches

2024-05-03 16:42 UTC, JamesKEbert commented on features/0193-coin-flip/README.md
> +- Authors: [Daniel Hardman](mailto:daniel.hardman@gmail.com), [Patrick Stürmlinger](pmailto:atrick@mindf.org)
```suggestion
- Authors: [Daniel Hardman](mailto:daniel.hardman@gmail.com), [Patrick Stürmlinger](mailto:patrick@mindf.org)
```

2024-05-03 16:42 UTC, JamesKEbert commented on concepts/0250-rich-schemas/README.md
>  - Author: [Ken Ebert](ken@sovrin.org), [Brent Zundel](brent.zundel@evernym.com)
Missing `mailto:`

2024-05-03 16:42 UTC, JamesKEbert commented on concepts/0217-linkable-message-paths/README.md
>  - Authors: [Daniel Hardman](daniel.hardman@gmail.com)
Missing `mailto:`

2024-05-03 16:42 UTC, JamesKEbert commented on concepts/0207-credential-fraud-threat-model/README.md
>  - Authors: [Daniel Hardman](daniel.hardman@gmail.com)
Missing `mailto:`

2024-05-03 16:42 UTC, JamesKEbert commented on concepts/0094-cross-domain-messaging/README.md
>  - Authors: [Stephen Curran](swcurran@gmail.com)
Missing `mailto:`

2024-05-03 16:42 UTC, JamesKEbert commented on concepts/0051-dkms/README.md
>  - Authors: [Drummond Reed](drummond@connect.me) et al.
Missing `mailto:`

2024-05-03 16:42 UTC, JamesKEbert commented on concepts/0029-message-trust-contexts/README.md
>  - Authors: [Daniel Hardman](daniel.hardman@gmail.com)
Missing `mailto:`

2024-05-03 16:42 UTC, JamesKEbert commented on concepts/0017-attachments/README.md
>  - Authors: [Daniel Hardman](daniel.hardman@gmail.com), Sam Curren, Andrew Whitehead
Missing `mailto:`

2024-05-03 16:58 UTC, JamesKEbert approved these changes
LGTM

2024-05-03 17:47 UTC, WadeBarnes approved these changes

2024-05-03 17:47 UTC, merged